name: Cleanup Old Releases
  on:
    release:
      types: [published]
    workflow_dispatch:
  permissions:
    contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup Public Releases
      run: |
        gh release list --limit 10 --json name,tagName --jq '.[] | select(.creator.login == "github-actions[bot]") | .tagName' | xargs -I {} gh release delete {} --yes

    - name: Cleanup Private Releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release list --limit 10 --json name,tagName --jq '.[] | select(.creator.login == "github-actions[bot]") | .tagName' | xargs -I {} gh release delete {} --yes

    - name: Summary
      run: echo "Cleanup completed!"