name: Cleanup Action Logs


on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch: 

permissions:
  actions: write
  contents: read

jobs:
  delete-history:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraider/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
